name: tunisie_catering_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  web_socket_channel: ^2.4.0
  intl: ^0.18.1 # Version la plus récente
  image_picker: ^1.0.4
  mobile_scanner: ^3.0.0
  provider: ^6.0.5
  badges: ^2.0.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/cash.png
    - assets/icons/availabale.jpg
    - assets/icons/unaivalable.jpg
